export default {
  COUNTRIES: 'COUNTRIES',
  REGIONS: 'REGIONS',
  WEBCAMS: 'WEBCAMS',
  WEBCAM_COUNTER: 'WEBCAM_COUNTER',
  CURRENT_COUNTRY: 'CURRENT_COUNTRY',

  TAGS_ADD_TAG: 'TAGS_ADD_TAG',
  TAGS_ADD_WEBCAM: 'TAGS_ADD_WEBCAM',
};
