export default {
  COUNTRIES: 'COUNTRIES',
  REGIONS: 'REGIONS',
  WEBCAMS: 'WEBCAMS',
  WEBCAM_COUNTER: 'WEBCAM_COUNTER',
  CURRENT_COUNTRY: 'CURRENT_COUNTRY',
  CURRENT_PAGE: 'CURRENT_PAGE',
  CURRENT_REGION: 'CURRENT_REGION',

  TAGS_ADD_TAG: 'TAGS_ADD_TAG',
  TAGS_ADD_WEBCAM: 'TAGS_ADD_WEBCAM',
  TAGS_SET_SELECTED_TAGS: 'TAGS_SET_SELECTED_TAGS',
  TAGS_SET_TAGNAME: 'TAGS_SET_TAGNAME',
  TAGS_DELETE_TAG: 'TAGS_DELETE_TAG',
};
